#! /usr/bin/env python3
import dash 
import dash_core_components as dcc
import dash_html_components as html
from getData import getData_4


d1 = getData_4('device_01')
d2 = getData_4('device_02')
print(d1['x'][0])

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

app.layout = html.Div(children=[
    html.H1(children='Sample Dash'),
    
    html.Div(children= ''' 
        Data is currently autogenerated from within server and sent to SQL
        
        '''),
    

    dcc.Graph(
        id='sample-graph',
        # main plot here
        figure={
            'data' :[
                {'x': d1['x'], 'y' : d1['y'], 'type': 'line', 'name' : 'd_1'},
                {'x': d2['x'], 'y' : d2['y'], 'type': 'line', 'name' : 'd_2'},

                ],
            'layout': {
                'title':'Simulated data'
            }
        }
    )
])

if __name__ == '__main__':
    app.run_server(debug=True, host='0.0.0.0', port = 8084)
